### ISSUE TITLE
Uncaught RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by baur** [cycjimmy/jsmpeg-player#33]
**Describe the bug**

**To Reproduce**
Show more than 10 camera and click **F5** 2,3-times

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome

**Sometimes I get an error:**

```
00025b06-49:22 Uncaught RuntimeError: memory access out of bounds
    at wasm-function[49]:0x55ea
    at wasm-function[2]:0x3f4
    at i.e.initializeWasmDecoder (http://host:2000/jsmpeg-player.umd.min.js:6:39060)
    at i.e.bufferWrite (http://host:2000/jsmpeg-player.umd.min.js:6:39456)
    at i.t.write (http://host:2000/jsmpeg-player.umd.min.js:6:18529)
    at i.e.write (http://host:2000/jsmpeg-player.umd.min.js:6:39769)
    at A.t.packetComplete (http://host:2000/jsmpeg-player.umd.min.js:6:17605)
    at A.t.parsePacket (http://host:2000/jsmpeg-player.umd.min.js:6:16214)
    at A.t.write (http://host:2000/jsmpeg-player.umd.min.js:6:15740)
    at A.t.onMessage (http://host:2000/jsmpeg-player.umd.min.js:6:13033)

```

**Comment by samuelsit** [comment]
Same but with 1 camera
